// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Client represents an OAuth2 client that is managed by the storage provider.
type Client struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	RedirectUris         []string `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TrustedPeers         []string `protobuf:"bytes,4,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	Public               bool     `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl              string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Client) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *Client) GetTrustedPeers() []string {
	if m != nil {
		return m.TrustedPeers
	}
	return nil
}

func (m *Client) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

// CreateClientReq is a request to add a client to the storage service.
// Will not work on static clients
type CreateClientReq struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientReq) Reset()         { *m = CreateClientReq{} }
func (m *CreateClientReq) String() string { return proto.CompactTextString(m) }
func (*CreateClientReq) ProtoMessage()    {}
func (*CreateClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{1}
}

func (m *CreateClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientReq.Unmarshal(m, b)
}
func (m *CreateClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientReq.Marshal(b, m, deterministic)
}
func (m *CreateClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientReq.Merge(m, src)
}
func (m *CreateClientReq) XXX_Size() int {
	return xxx_messageInfo_CreateClientReq.Size(m)
}
func (m *CreateClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientReq proto.InternalMessageInfo

func (m *CreateClientReq) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

// CreateClientResp returns the response from creating a client.
type CreateClientResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResp) Reset()         { *m = CreateClientResp{} }
func (m *CreateClientResp) String() string { return proto.CompactTextString(m) }
func (*CreateClientResp) ProtoMessage()    {}
func (*CreateClientResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{2}
}

func (m *CreateClientResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResp.Unmarshal(m, b)
}
func (m *CreateClientResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResp.Marshal(b, m, deterministic)
}
func (m *CreateClientResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResp.Merge(m, src)
}
func (m *CreateClientResp) XXX_Size() int {
	return xxx_messageInfo_CreateClientResp.Size(m)
}
func (m *CreateClientResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResp proto.InternalMessageInfo

// DeleteClientReq is a request to delete a client from the storage service.
// Will not work on static clients
type DeleteClientReq struct {
	// The ID of the client.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientReq) Reset()         { *m = DeleteClientReq{} }
func (m *DeleteClientReq) String() string { return proto.CompactTextString(m) }
func (*DeleteClientReq) ProtoMessage()    {}
func (*DeleteClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{3}
}

func (m *DeleteClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientReq.Unmarshal(m, b)
}
func (m *DeleteClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientReq.Marshal(b, m, deterministic)
}
func (m *DeleteClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientReq.Merge(m, src)
}
func (m *DeleteClientReq) XXX_Size() int {
	return xxx_messageInfo_DeleteClientReq.Size(m)
}
func (m *DeleteClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientReq proto.InternalMessageInfo

func (m *DeleteClientReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteClientResp determines if the client is deleted successfully.
type DeleteClientResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientResp) Reset()         { *m = DeleteClientResp{} }
func (m *DeleteClientResp) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResp) ProtoMessage()    {}
func (*DeleteClientResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{4}
}

func (m *DeleteClientResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResp.Unmarshal(m, b)
}
func (m *DeleteClientResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResp.Marshal(b, m, deterministic)
}
func (m *DeleteClientResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResp.Merge(m, src)
}
func (m *DeleteClientResp) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResp.Size(m)
}
func (m *DeleteClientResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResp proto.InternalMessageInfo

// UpdateClientReq is a request to update an existing client stored in the storage service.
// Will not work on static clients
type UpdateClientReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RedirectUris         []string `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TrustedPeers         []string `protobuf:"bytes,3,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl              string   `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClientReq) Reset()         { *m = UpdateClientReq{} }
func (m *UpdateClientReq) String() string { return proto.CompactTextString(m) }
func (*UpdateClientReq) ProtoMessage()    {}
func (*UpdateClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{5}
}

func (m *UpdateClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientReq.Unmarshal(m, b)
}
func (m *UpdateClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientReq.Marshal(b, m, deterministic)
}
func (m *UpdateClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientReq.Merge(m, src)
}
func (m *UpdateClientReq) XXX_Size() int {
	return xxx_messageInfo_UpdateClientReq.Size(m)
}
func (m *UpdateClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientReq proto.InternalMessageInfo

func (m *UpdateClientReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateClientReq) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *UpdateClientReq) GetTrustedPeers() []string {
	if m != nil {
		return m.TrustedPeers
	}
	return nil
}

func (m *UpdateClientReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateClientReq) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

// UpdateClientResp returns the response form updating a client.
type UpdateClientResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClientResp) Reset()         { *m = UpdateClientResp{} }
func (m *UpdateClientResp) String() string { return proto.CompactTextString(m) }
func (*UpdateClientResp) ProtoMessage()    {}
func (*UpdateClientResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{6}
}

func (m *UpdateClientResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientResp.Unmarshal(m, b)
}
func (m *UpdateClientResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientResp.Marshal(b, m, deterministic)
}
func (m *UpdateClientResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientResp.Merge(m, src)
}
func (m *UpdateClientResp) XXX_Size() int {
	return xxx_messageInfo_UpdateClientResp.Size(m)
}
func (m *UpdateClientResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientResp proto.InternalMessageInfo

// ListClientsReq is a request to get a list clients
// Will not work on static clients
// TODO Add pagination / sorting when internal API offers it?
type ListClientsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClientsReq) Reset()         { *m = ListClientsReq{} }
func (m *ListClientsReq) String() string { return proto.CompactTextString(m) }
func (*ListClientsReq) ProtoMessage()    {}
func (*ListClientsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{7}
}

func (m *ListClientsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsReq.Unmarshal(m, b)
}
func (m *ListClientsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsReq.Marshal(b, m, deterministic)
}
func (m *ListClientsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsReq.Merge(m, src)
}
func (m *ListClientsReq) XXX_Size() int {
	return xxx_messageInfo_ListClientsReq.Size(m)
}
func (m *ListClientsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsReq proto.InternalMessageInfo

// ListClientsResp returns an array of non-static clients
// TODO Add pagination information when internal API offers it?
type ListClientsResp struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListClientsResp) Reset()         { *m = ListClientsResp{} }
func (m *ListClientsResp) String() string { return proto.CompactTextString(m) }
func (*ListClientsResp) ProtoMessage()    {}
func (*ListClientsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{8}
}

func (m *ListClientsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsResp.Unmarshal(m, b)
}
func (m *ListClientsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsResp.Marshal(b, m, deterministic)
}
func (m *ListClientsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsResp.Merge(m, src)
}
func (m *ListClientsResp) XXX_Size() int {
	return xxx_messageInfo_ListClientsResp.Size(m)
}
func (m *ListClientsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsResp proto.InternalMessageInfo

func (m *ListClientsResp) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

// Password is an email for password mapping managed by the storage.
type Password struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Currently we do not accept plain text passwords. Could be an option in the future.
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Password) Reset()         { *m = Password{} }
func (m *Password) String() string { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()    {}
func (*Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{9}
}

func (m *Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Password.Unmarshal(m, b)
}
func (m *Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Password.Marshal(b, m, deterministic)
}
func (m *Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Password.Merge(m, src)
}
func (m *Password) XXX_Size() int {
	return xxx_messageInfo_Password.Size(m)
}
func (m *Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Password proto.InternalMessageInfo

func (m *Password) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Password) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Password) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Password) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// CreatePasswordReq is a request to add a password/user to the storage service.
// Will not work on static passwords
type CreatePasswordReq struct {
	Password             *Password `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePasswordReq) Reset()         { *m = CreatePasswordReq{} }
func (m *CreatePasswordReq) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordReq) ProtoMessage()    {}
func (*CreatePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{10}
}

func (m *CreatePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordReq.Unmarshal(m, b)
}
func (m *CreatePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordReq.Marshal(b, m, deterministic)
}
func (m *CreatePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordReq.Merge(m, src)
}
func (m *CreatePasswordReq) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordReq.Size(m)
}
func (m *CreatePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordReq proto.InternalMessageInfo

func (m *CreatePasswordReq) GetPassword() *Password {
	if m != nil {
		return m.Password
	}
	return nil
}

// CreatePasswordResp returns the response from creating a password.
type CreatePasswordResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResp) Reset()         { *m = CreatePasswordResp{} }
func (m *CreatePasswordResp) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResp) ProtoMessage()    {}
func (*CreatePasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{11}
}

func (m *CreatePasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResp.Unmarshal(m, b)
}
func (m *CreatePasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResp.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResp.Merge(m, src)
}
func (m *CreatePasswordResp) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResp.Size(m)
}
func (m *CreatePasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResp proto.InternalMessageInfo

// UpdatePasswordReq is a request to modify an existing password/user stored in the storage service.
// Will not work on static passwords
type UpdatePasswordReq struct {
	// The email used to lookup the password. This field cannot be modified
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewHash              []byte   `protobuf:"bytes,2,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	NewUsername          string   `protobuf:"bytes,3,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordReq) Reset()         { *m = UpdatePasswordReq{} }
func (m *UpdatePasswordReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordReq) ProtoMessage()    {}
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{12}
}

func (m *UpdatePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordReq.Unmarshal(m, b)
}
func (m *UpdatePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordReq.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordReq.Merge(m, src)
}
func (m *UpdatePasswordReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordReq.Size(m)
}
func (m *UpdatePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordReq proto.InternalMessageInfo

func (m *UpdatePasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatePasswordReq) GetNewHash() []byte {
	if m != nil {
		return m.NewHash
	}
	return nil
}

func (m *UpdatePasswordReq) GetNewUsername() string {
	if m != nil {
		return m.NewUsername
	}
	return ""
}

// UpdatePasswordResp returns the response from modifying an existing password.
type UpdatePasswordResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResp) Reset()         { *m = UpdatePasswordResp{} }
func (m *UpdatePasswordResp) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResp) ProtoMessage()    {}
func (*UpdatePasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{13}
}

func (m *UpdatePasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResp.Unmarshal(m, b)
}
func (m *UpdatePasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResp.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResp.Merge(m, src)
}
func (m *UpdatePasswordResp) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResp.Size(m)
}
func (m *UpdatePasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResp proto.InternalMessageInfo

// DeletePasswordReq is a request to delete a password/user stored in the storage service.
// Will not work on static passwords
type DeletePasswordReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePasswordReq) Reset()         { *m = DeletePasswordReq{} }
func (m *DeletePasswordReq) String() string { return proto.CompactTextString(m) }
func (*DeletePasswordReq) ProtoMessage()    {}
func (*DeletePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{14}
}

func (m *DeletePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePasswordReq.Unmarshal(m, b)
}
func (m *DeletePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePasswordReq.Marshal(b, m, deterministic)
}
func (m *DeletePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePasswordReq.Merge(m, src)
}
func (m *DeletePasswordReq) XXX_Size() int {
	return xxx_messageInfo_DeletePasswordReq.Size(m)
}
func (m *DeletePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePasswordReq proto.InternalMessageInfo

func (m *DeletePasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// DeletePasswordResp returns the response from deleting a password.
type DeletePasswordResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePasswordResp) Reset()         { *m = DeletePasswordResp{} }
func (m *DeletePasswordResp) String() string { return proto.CompactTextString(m) }
func (*DeletePasswordResp) ProtoMessage()    {}
func (*DeletePasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{15}
}

func (m *DeletePasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePasswordResp.Unmarshal(m, b)
}
func (m *DeletePasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePasswordResp.Marshal(b, m, deterministic)
}
func (m *DeletePasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePasswordResp.Merge(m, src)
}
func (m *DeletePasswordResp) XXX_Size() int {
	return xxx_messageInfo_DeletePasswordResp.Size(m)
}
func (m *DeletePasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePasswordResp proto.InternalMessageInfo

// ListPasswordReq is a request to list the passwords/users stored in the storage service.
type ListPasswordReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPasswordReq) Reset()         { *m = ListPasswordReq{} }
func (m *ListPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ListPasswordReq) ProtoMessage()    {}
func (*ListPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{16}
}

func (m *ListPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPasswordReq.Unmarshal(m, b)
}
func (m *ListPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPasswordReq.Marshal(b, m, deterministic)
}
func (m *ListPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPasswordReq.Merge(m, src)
}
func (m *ListPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ListPasswordReq.Size(m)
}
func (m *ListPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPasswordReq proto.InternalMessageInfo

// ListPasswordResp returns a list of passwords.
type ListPasswordResp struct {
	Passwords            []*Password `protobuf:"bytes,1,rep,name=passwords,proto3" json:"passwords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPasswordResp) Reset()         { *m = ListPasswordResp{} }
func (m *ListPasswordResp) String() string { return proto.CompactTextString(m) }
func (*ListPasswordResp) ProtoMessage()    {}
func (*ListPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{17}
}

func (m *ListPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPasswordResp.Unmarshal(m, b)
}
func (m *ListPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPasswordResp.Marshal(b, m, deterministic)
}
func (m *ListPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPasswordResp.Merge(m, src)
}
func (m *ListPasswordResp) XXX_Size() int {
	return xxx_messageInfo_ListPasswordResp.Size(m)
}
func (m *ListPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListPasswordResp proto.InternalMessageInfo

func (m *ListPasswordResp) GetPasswords() []*Password {
	if m != nil {
		return m.Passwords
	}
	return nil
}

// VerifyPasswordReq will allow someone to verify if a given username and password combination exist in the system
// Will not work on static passwords
type VerifyPasswordReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordReq) Reset()         { *m = VerifyPasswordReq{} }
func (m *VerifyPasswordReq) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordReq) ProtoMessage()    {}
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{18}
}

func (m *VerifyPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordReq.Unmarshal(m, b)
}
func (m *VerifyPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordReq.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordReq.Merge(m, src)
}
func (m *VerifyPasswordReq) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordReq.Size(m)
}
func (m *VerifyPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordReq proto.InternalMessageInfo

func (m *VerifyPasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// VerifyPasswordResp returns whether or not there was an email and password match
// If there is no email associated, a NOT_FOUND status will be returned
type VerifyPasswordResp struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordResp) Reset()         { *m = VerifyPasswordResp{} }
func (m *VerifyPasswordResp) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordResp) ProtoMessage()    {}
func (*VerifyPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{19}
}

func (m *VerifyPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordResp.Unmarshal(m, b)
}
func (m *VerifyPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordResp.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordResp.Merge(m, src)
}
func (m *VerifyPasswordResp) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordResp.Size(m)
}
func (m *VerifyPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordResp proto.InternalMessageInfo

func (m *VerifyPasswordResp) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

// RefreshTokenRef contains the metadata for a refresh token that is managed by the storage.
type RefreshTokenRef struct {
	// ID of the refresh token.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed             int64    `protobuf:"varint,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRef) Reset()         { *m = RefreshTokenRef{} }
func (m *RefreshTokenRef) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRef) ProtoMessage()    {}
func (*RefreshTokenRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{20}
}

func (m *RefreshTokenRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRef.Unmarshal(m, b)
}
func (m *RefreshTokenRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRef.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRef.Merge(m, src)
}
func (m *RefreshTokenRef) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRef.Size(m)
}
func (m *RefreshTokenRef) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRef.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRef proto.InternalMessageInfo

func (m *RefreshTokenRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefreshTokenRef) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RefreshTokenRef) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RefreshTokenRef) GetLastUsed() int64 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

// ListRefreshReq is a request to enumerate the refresh tokens of a user that is managed by the storage.
type ListRefreshForUserReq struct {
	// The "sub" claim returned in the ID Token.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRefreshForUserReq) Reset()         { *m = ListRefreshForUserReq{} }
func (m *ListRefreshForUserReq) String() string { return proto.CompactTextString(m) }
func (*ListRefreshForUserReq) ProtoMessage()    {}
func (*ListRefreshForUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{21}
}

func (m *ListRefreshForUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRefreshForUserReq.Unmarshal(m, b)
}
func (m *ListRefreshForUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRefreshForUserReq.Marshal(b, m, deterministic)
}
func (m *ListRefreshForUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRefreshForUserReq.Merge(m, src)
}
func (m *ListRefreshForUserReq) XXX_Size() int {
	return xxx_messageInfo_ListRefreshForUserReq.Size(m)
}
func (m *ListRefreshForUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRefreshForUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListRefreshForUserReq proto.InternalMessageInfo

func (m *ListRefreshForUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// ListRefreshResp returns a list of refresh tokens for a user.
type ListRefreshForUserResp struct {
	RefreshTokens        []*RefreshTokenRef `protobuf:"bytes,1,rep,name=refresh_tokens,json=refreshTokens,proto3" json:"refresh_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRefreshForUserResp) Reset()         { *m = ListRefreshForUserResp{} }
func (m *ListRefreshForUserResp) String() string { return proto.CompactTextString(m) }
func (*ListRefreshForUserResp) ProtoMessage()    {}
func (*ListRefreshForUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{22}
}

func (m *ListRefreshForUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRefreshForUserResp.Unmarshal(m, b)
}
func (m *ListRefreshForUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRefreshForUserResp.Marshal(b, m, deterministic)
}
func (m *ListRefreshForUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRefreshForUserResp.Merge(m, src)
}
func (m *ListRefreshForUserResp) XXX_Size() int {
	return xxx_messageInfo_ListRefreshForUserResp.Size(m)
}
func (m *ListRefreshForUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRefreshForUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListRefreshForUserResp proto.InternalMessageInfo

func (m *ListRefreshForUserResp) GetRefreshTokens() []*RefreshTokenRef {
	if m != nil {
		return m.RefreshTokens
	}
	return nil
}

// RevokeRefreshReq is a request to revoke the refresh token of the user-client pair that is managed by the storage.
type RevokeRefreshReq struct {
	// The "sub" claim returned in the ID Token.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeRefreshReq) Reset()         { *m = RevokeRefreshReq{} }
func (m *RevokeRefreshReq) String() string { return proto.CompactTextString(m) }
func (*RevokeRefreshReq) ProtoMessage()    {}
func (*RevokeRefreshReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{23}
}

func (m *RevokeRefreshReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeRefreshReq.Unmarshal(m, b)
}
func (m *RevokeRefreshReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeRefreshReq.Marshal(b, m, deterministic)
}
func (m *RevokeRefreshReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeRefreshReq.Merge(m, src)
}
func (m *RevokeRefreshReq) XXX_Size() int {
	return xxx_messageInfo_RevokeRefreshReq.Size(m)
}
func (m *RevokeRefreshReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeRefreshReq.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeRefreshReq proto.InternalMessageInfo

func (m *RevokeRefreshReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RevokeRefreshReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// RevokeRefreshResp determines if the refresh token is revoked successfully.
type RevokeRefreshResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeRefreshResp) Reset()         { *m = RevokeRefreshResp{} }
func (m *RevokeRefreshResp) String() string { return proto.CompactTextString(m) }
func (*RevokeRefreshResp) ProtoMessage()    {}
func (*RevokeRefreshResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{24}
}

func (m *RevokeRefreshResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeRefreshResp.Unmarshal(m, b)
}
func (m *RevokeRefreshResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeRefreshResp.Marshal(b, m, deterministic)
}
func (m *RevokeRefreshResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeRefreshResp.Merge(m, src)
}
func (m *RevokeRefreshResp) XXX_Size() int {
	return xxx_messageInfo_RevokeRefreshResp.Size(m)
}
func (m *RevokeRefreshResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeRefreshResp.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeRefreshResp proto.InternalMessageInfo

// VersionReq is a request to fetch version info.
type VersionReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReq) Reset()         { *m = VersionReq{} }
func (m *VersionReq) String() string { return proto.CompactTextString(m) }
func (*VersionReq) ProtoMessage()    {}
func (*VersionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{25}
}

func (m *VersionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReq.Unmarshal(m, b)
}
func (m *VersionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReq.Marshal(b, m, deterministic)
}
func (m *VersionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReq.Merge(m, src)
}
func (m *VersionReq) XXX_Size() int {
	return xxx_messageInfo_VersionReq.Size(m)
}
func (m *VersionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReq.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReq proto.InternalMessageInfo

// VersionResp holds the version info of components.
type VersionResp struct {
	// Semantic version of the server.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Version of the API. It increases every time a new call is added to the API.
	// Clients should use this info to determine if the server supports specific features.
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResp) Reset()         { *m = VersionResp{} }
func (m *VersionResp) String() string { return proto.CompactTextString(m) }
func (*VersionResp) ProtoMessage()    {}
func (*VersionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c159bad8e0d3e71, []int{26}
}

func (m *VersionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResp.Unmarshal(m, b)
}
func (m *VersionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResp.Marshal(b, m, deterministic)
}
func (m *VersionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResp.Merge(m, src)
}
func (m *VersionResp) XXX_Size() int {
	return xxx_messageInfo_VersionResp.Size(m)
}
func (m *VersionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResp.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResp proto.InternalMessageInfo

func (m *VersionResp) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *VersionResp) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "v1alpha1.Client")
	proto.RegisterType((*CreateClientReq)(nil), "v1alpha1.CreateClientReq")
	proto.RegisterType((*CreateClientResp)(nil), "v1alpha1.CreateClientResp")
	proto.RegisterType((*DeleteClientReq)(nil), "v1alpha1.DeleteClientReq")
	proto.RegisterType((*DeleteClientResp)(nil), "v1alpha1.DeleteClientResp")
	proto.RegisterType((*UpdateClientReq)(nil), "v1alpha1.UpdateClientReq")
	proto.RegisterType((*UpdateClientResp)(nil), "v1alpha1.UpdateClientResp")
	proto.RegisterType((*ListClientsReq)(nil), "v1alpha1.ListClientsReq")
	proto.RegisterType((*ListClientsResp)(nil), "v1alpha1.ListClientsResp")
	proto.RegisterType((*Password)(nil), "v1alpha1.Password")
	proto.RegisterType((*CreatePasswordReq)(nil), "v1alpha1.CreatePasswordReq")
	proto.RegisterType((*CreatePasswordResp)(nil), "v1alpha1.CreatePasswordResp")
	proto.RegisterType((*UpdatePasswordReq)(nil), "v1alpha1.UpdatePasswordReq")
	proto.RegisterType((*UpdatePasswordResp)(nil), "v1alpha1.UpdatePasswordResp")
	proto.RegisterType((*DeletePasswordReq)(nil), "v1alpha1.DeletePasswordReq")
	proto.RegisterType((*DeletePasswordResp)(nil), "v1alpha1.DeletePasswordResp")
	proto.RegisterType((*ListPasswordReq)(nil), "v1alpha1.ListPasswordReq")
	proto.RegisterType((*ListPasswordResp)(nil), "v1alpha1.ListPasswordResp")
	proto.RegisterType((*VerifyPasswordReq)(nil), "v1alpha1.VerifyPasswordReq")
	proto.RegisterType((*VerifyPasswordResp)(nil), "v1alpha1.VerifyPasswordResp")
	proto.RegisterType((*RefreshTokenRef)(nil), "v1alpha1.RefreshTokenRef")
	proto.RegisterType((*ListRefreshForUserReq)(nil), "v1alpha1.ListRefreshForUserReq")
	proto.RegisterType((*ListRefreshForUserResp)(nil), "v1alpha1.ListRefreshForUserResp")
	proto.RegisterType((*RevokeRefreshReq)(nil), "v1alpha1.RevokeRefreshReq")
	proto.RegisterType((*RevokeRefreshResp)(nil), "v1alpha1.RevokeRefreshResp")
	proto.RegisterType((*VersionReq)(nil), "v1alpha1.VersionReq")
	proto.RegisterType((*VersionResp)(nil), "v1alpha1.VersionResp")
}

func init() { proto.RegisterFile("api/v1alpha1/api.proto", fileDescriptor_1c159bad8e0d3e71) }

var fileDescriptor_1c159bad8e0d3e71 = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xb6, 0x33, 0x89, 0x3d, 0xae, 0x38, 0xb1, 0x5d, 0x64, 0x83, 0x33, 0x01, 0xe1, 0x6d, 0x2e,
	0x81, 0x83, 0xf7, 0x87, 0x03, 0x87, 0x15, 0x12, 0x90, 0xc0, 0x66, 0x11, 0x48, 0xab, 0x11, 0x5e,
	0x09, 0x2e, 0xd6, 0xc4, 0x53, 0x89, 0x5b, 0x3b, 0xf1, 0xf4, 0x76, 0x8f, 0x93, 0x85, 0x47, 0xe1,
	0x6d, 0xb8, 0xf2, 0x54, 0xa8, 0x7b, 0x7a, 0x9c, 0x9e, 0x9f, 0x64, 0xf7, 0x94, 0xa9, 0xea, 0xaa,
	0xaf, 0xba, 0xbe, 0xea, 0xfa, 0x62, 0x38, 0x8c, 0x04, 0x7f, 0x72, 0xf3, 0x2c, 0x4a, 0xc4, 0x32,
	0x7a, 0xf6, 0x24, 0x12, 0x7c, 0x2a, 0x64, 0x9a, 0xa5, 0xe8, 0x17, 0x3e, 0xf6, 0x6f, 0x1b, 0x3a,
	0xa7, 0x09, 0xa7, 0x55, 0x86, 0xfb, 0xb0, 0xc5, 0xe3, 0x71, 0x7b, 0xd2, 0x3e, 0xe9, 0x85, 0x5b,
	0x3c, 0xc6, 0x43, 0xe8, 0x28, 0x5a, 0x48, 0xca, 0xc6, 0x5b, 0xc6, 0x67, 0x2d, 0xfc, 0x12, 0xf6,
	0x24, 0xc5, 0x5c, 0xd2, 0x22, 0x9b, 0xaf, 0x25, 0x57, 0x63, 0x6f, 0xe2, 0x9d, 0xf4, 0xc2, 0x7e,
	0xe1, 0x9c, 0x49, 0xae, 0x74, 0x50, 0x26, 0xd7, 0x2a, 0xa3, 0x78, 0x2e, 0x88, 0xa4, 0x1a, 0x6f,
	0xe7, 0x41, 0xd6, 0xf9, 0x5a, 0xfb, 0x74, 0x05, 0xb1, 0xbe, 0x48, 0xf8, 0x62, 0xbc, 0x33, 0x69,
	0x9f, 0xf8, 0xa1, 0xb5, 0x10, 0x61, 0x7b, 0x15, 0x5d, 0xd3, 0xb8, 0x63, 0xea, 0x9a, 0x6f, 0x3c,
	0x02, 0x3f, 0x49, 0xaf, 0xd2, 0xf9, 0x5a, 0x26, 0xe3, 0xae, 0xf1, 0x77, 0xb5, 0x3d, 0x93, 0x09,
	0x7b, 0x01, 0x83, 0x53, 0x49, 0x51, 0x46, 0x79, 0x23, 0x21, 0xbd, 0xc3, 0x13, 0xe8, 0x2c, 0x8c,
	0x61, 0xfa, 0xd9, 0x7d, 0x3e, 0x9c, 0x16, 0x1d, 0x4f, 0x6d, 0x90, 0x3d, 0x67, 0x08, 0xc3, 0x72,
	0xb2, 0x12, 0xec, 0x31, 0x0c, 0xce, 0x28, 0x21, 0x17, 0xb0, 0x42, 0x8e, 0x4e, 0x2b, 0x87, 0x28,
	0xc1, 0xfe, 0x69, 0xc3, 0x60, 0x26, 0xe2, 0xe8, 0x81, 0xbc, 0x3a, 0x79, 0x5b, 0x1f, 0x43, 0x9e,
	0xd7, 0x40, 0x5e, 0x41, 0xd2, 0xf6, 0x3d, 0x24, 0xed, 0x94, 0x49, 0x42, 0x18, 0x96, 0xef, 0xa6,
	0x04, 0x1b, 0xc2, 0xfe, 0xaf, 0x5c, 0x65, 0xb9, 0x47, 0x85, 0xf4, 0x8e, 0x7d, 0x07, 0x83, 0x92,
	0x47, 0x09, 0xfc, 0x1a, 0xba, 0x39, 0x55, 0x6a, 0xdc, 0x9e, 0x78, 0x8d, 0x5c, 0x16, 0x01, 0x8c,
	0x83, 0xff, 0x3a, 0x52, 0xea, 0x36, 0x95, 0x31, 0x1e, 0xc0, 0x0e, 0x5d, 0x47, 0x3c, 0xb1, 0xcd,
	0xe7, 0x86, 0xbe, 0xf5, 0x32, 0x52, 0x4b, 0xf3, 0xa4, 0xfa, 0xa1, 0xf9, 0xc6, 0x00, 0xfc, 0xb5,
	0x22, 0x69, 0xba, 0xf1, 0x4c, 0xf0, 0xc6, 0xc6, 0x4f, 0xa1, 0xab, 0xbf, 0xe7, 0x3c, 0xb6, 0x8d,
	0x76, 0xb4, 0xf9, 0x2a, 0x66, 0xa7, 0x30, 0xca, 0xe7, 0x56, 0x14, 0xd4, 0x6c, 0x4f, 0xc1, 0x17,
	0xd6, 0xb4, 0x83, 0xc7, 0xbb, 0xcb, 0x6e, 0x02, 0x37, 0x31, 0xec, 0x00, 0xb0, 0x0a, 0xa2, 0x04,
	0xbb, 0x82, 0x51, 0x4e, 0x95, 0x0b, 0xdd, 0xdc, 0xce, 0x11, 0xf8, 0x2b, 0xba, 0x9d, 0x3b, 0x2d,
	0x75, 0x57, 0x74, 0x7b, 0xae, 0xbb, 0x7a, 0x0c, 0x7d, 0x7d, 0x54, 0xe9, 0x6c, 0x77, 0x45, 0xb7,
	0x33, 0xeb, 0xd2, 0xe5, 0xab, 0x85, 0x94, 0x60, 0x5f, 0xc1, 0x28, 0x7f, 0x5a, 0x1f, 0x2c, 0xaf,
	0x01, 0xaa, 0xa1, 0x4a, 0xb0, 0x51, 0x3e, 0x44, 0x27, 0x9d, 0x9d, 0xc1, 0xb0, 0xec, 0x52, 0x02,
	0x9f, 0x42, 0xaf, 0x20, 0xa2, 0x18, 0x6d, 0x13, 0x5b, 0x77, 0x41, 0xec, 0x27, 0x18, 0xbd, 0x21,
	0xc9, 0x2f, 0xff, 0xfa, 0x30, 0x31, 0x81, 0x33, 0x89, 0x5c, 0x3e, 0xee, 0x58, 0x7f, 0x0a, 0x58,
	0x85, 0x51, 0x42, 0x67, 0xdc, 0x68, 0x2f, 0xa7, 0x7c, 0x76, 0x7e, 0xb8, 0xb1, 0xd9, 0xdf, 0x30,
	0x08, 0xe9, 0x52, 0x92, 0x5a, 0xfe, 0x9e, 0xbe, 0xa5, 0x55, 0x48, 0x97, 0xb5, 0xc5, 0x3a, 0x86,
	0x5e, 0xfe, 0x0a, 0xf5, 0x53, 0xb1, 0x15, 0x73, 0xc7, 0xab, 0x18, 0x3f, 0x07, 0x58, 0x98, 0x39,
	0xc7, 0xf3, 0x28, 0x33, 0x9b, 0xe1, 0x85, 0x3d, 0xeb, 0xf9, 0x21, 0xd3, 0xb9, 0x49, 0xa4, 0x32,
	0x3d, 0xab, 0xd8, 0x88, 0x8e, 0x17, 0xfa, 0xda, 0x31, 0x53, 0xa4, 0x6f, 0xfb, 0x48, 0x53, 0x67,
	0xeb, 0xff, 0x9c, 0x4a, 0x3d, 0x3e, 0xdd, 0xb8, 0xf3, 0x34, 0xdb, 0xa5, 0xa7, 0xf9, 0x27, 0x1c,
	0x36, 0x65, 0x28, 0x81, 0xdf, 0xc3, 0xbe, 0xcc, 0xbd, 0xf3, 0x4c, 0x37, 0x52, 0xf0, 0x7e, 0x74,
	0xc7, 0x7b, 0xa5, 0xcf, 0x70, 0x4f, 0x3a, 0x0e, 0xc5, 0xce, 0x61, 0x18, 0xd2, 0x4d, 0xfa, 0x96,
	0x6c, 0xdc, 0x43, 0x17, 0x79, 0x90, 0x13, 0xf6, 0x09, 0x8c, 0x2a, 0x48, 0x4a, 0xb0, 0x3e, 0xc0,
	0x1b, 0x92, 0x8a, 0xa7, 0x2b, 0xfd, 0x6a, 0xbe, 0x85, 0xdd, 0x8d, 0xa5, 0x44, 0xfe, 0x0f, 0x41,
	0xde, 0x90, 0x2c, 0xca, 0xe4, 0x16, 0x0e, 0xc1, 0x8b, 0x04, 0xb7, 0x05, 0xf4, 0xe7, 0xf3, 0xff,
	0x3a, 0xe0, 0x9d, 0xd1, 0x7b, 0x7c, 0x09, 0x7d, 0x57, 0x5c, 0xd1, 0xe9, 0xb3, 0xa2, 0xd8, 0x41,
	0x70, 0xdf, 0x91, 0x12, 0xac, 0xa5, 0x81, 0x5c, 0xf5, 0x72, 0x81, 0x2a, 0x8a, 0xeb, 0x02, 0xd5,
	0x04, 0xcf, 0x00, 0xb9, 0xba, 0xed, 0x02, 0x55, 0x24, 0xdf, 0x05, 0xaa, 0x49, 0x7d, 0x0b, 0x7f,
	0x83, 0xfd, 0xb2, 0x74, 0xe0, 0x71, 0xb5, 0x03, 0x67, 0x4b, 0x82, 0xcf, 0xee, 0x3f, 0x2c, 0xe0,
	0xca, 0x52, 0xe0, 0xc2, 0xd5, 0xd4, 0xc8, 0x85, 0x6b, 0x50, 0x10, 0x03, 0x57, 0x16, 0x06, 0x17,
	0xae, 0xa6, 0x2e, 0x2e, 0x5c, 0x83, 0x9e, 0xb4, 0xf0, 0x1c, 0xf6, 0x5c, 0xf9, 0x50, 0x2e, 0x6d,
	0x15, 0xa9, 0x71, 0x69, 0xab, 0x4a, 0x0e, 0x6b, 0xe1, 0x1f, 0x80, 0xf5, 0xdd, 0xc0, 0x2f, 0xca,
	0x39, 0xb5, 0x5d, 0x0b, 0x26, 0x0f, 0x07, 0x18, 0xe8, 0x5f, 0x60, 0xaf, 0xf4, 0xa0, 0x31, 0x70,
	0xb7, 0xaa, 0xbc, 0x33, 0xc1, 0xf1, 0xbd, 0x67, 0x05, 0x7f, 0x65, 0x89, 0x72, 0xf9, 0xab, 0x69,
	0xa0, 0xcb, 0x5f, 0x5d, 0xd9, 0x58, 0x0b, 0x5f, 0x00, 0xbc, 0xa4, 0xcc, 0xee, 0x12, 0x1e, 0x94,
	0xa2, 0xed, 0xb2, 0x05, 0x8f, 0x1a, 0xbc, 0x3a, 0xf9, 0xc7, 0x63, 0x38, 0x5a, 0xa4, 0xd7, 0xd3,
	0x2b, 0x9e, 0x2d, 0xd7, 0x17, 0xd3, 0x98, 0xde, 0xf3, 0x58, 0xe8, 0x3f, 0xd3, 0x48, 0xf0, 0x8b,
	0x8e, 0xf9, 0x41, 0xf7, 0xcd, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xe3, 0xe4, 0xa3, 0xea,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DexClient is the client API for Dex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DexClient interface {
	// Client-centric RPCs
	// CreateClient creates a client.
	CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error)
	// UpdateClient updates an existing client
	UpdateClient(ctx context.Context, in *UpdateClientReq, opts ...grpc.CallOption) (*UpdateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error)
	// Password-centric RPCs
	// CreatePassword creates a password.
	CreatePassword(ctx context.Context, in *CreatePasswordReq, opts ...grpc.CallOption) (*CreatePasswordResp, error)
	// UpdatePassword modifies existing password.
	UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error)
	// DeletePassword deletes the password.
	DeletePassword(ctx context.Context, in *DeletePasswordReq, opts ...grpc.CallOption) (*DeletePasswordResp, error)
	// ListPassword lists all password entries.
	ListPasswords(ctx context.Context, in *ListPasswordReq, opts ...grpc.CallOption) (*ListPasswordResp, error)
	// Refresh Token-centric RPCs
	// ListRefresh lists all the refresh token entries for a particular user.
	ListRefreshForUser(ctx context.Context, in *ListRefreshForUserReq, opts ...grpc.CallOption) (*ListRefreshForUserResp, error)
	// RevokeRefresh revokes the refresh token for the provided user-client pair.
	RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error)
	// VerifyPassword returns whether a password matches a hash for a specific email or not.
	VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error)
	// Misc RPCs
	// GetVersion returns version information of the server.
	GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error)
}

type dexClient struct {
	cc *grpc.ClientConn
}

func NewDexClient(cc *grpc.ClientConn) DexClient {
	return &dexClient{cc}
}

func (c *dexClient) CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error) {
	out := new(CreateClientResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) UpdateClient(ctx context.Context, in *UpdateClientReq, opts ...grpc.CallOption) (*UpdateClientResp, error) {
	out := new(UpdateClientResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/UpdateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error) {
	out := new(DeleteClientResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/DeleteClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) CreatePassword(ctx context.Context, in *CreatePasswordReq, opts ...grpc.CallOption) (*CreatePasswordResp, error) {
	out := new(CreatePasswordResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/CreatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error) {
	out := new(UpdatePasswordResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) DeletePassword(ctx context.Context, in *DeletePasswordReq, opts ...grpc.CallOption) (*DeletePasswordResp, error) {
	out := new(DeletePasswordResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/DeletePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) ListPasswords(ctx context.Context, in *ListPasswordReq, opts ...grpc.CallOption) (*ListPasswordResp, error) {
	out := new(ListPasswordResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/ListPasswords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) ListRefreshForUser(ctx context.Context, in *ListRefreshForUserReq, opts ...grpc.CallOption) (*ListRefreshForUserResp, error) {
	out := new(ListRefreshForUserResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/ListRefreshForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error) {
	out := new(RevokeRefreshResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/RevokeRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error) {
	out := new(VerifyPasswordResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/VerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error) {
	out := new(VersionResp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Dex/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DexServer is the server API for Dex service.
type DexServer interface {
	// Client-centric RPCs
	// CreateClient creates a client.
	CreateClient(context.Context, *CreateClientReq) (*CreateClientResp, error)
	// UpdateClient updates an existing client
	UpdateClient(context.Context, *UpdateClientReq) (*UpdateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(context.Context, *DeleteClientReq) (*DeleteClientResp, error)
	// Password-centric RPCs
	// CreatePassword creates a password.
	CreatePassword(context.Context, *CreatePasswordReq) (*CreatePasswordResp, error)
	// UpdatePassword modifies existing password.
	UpdatePassword(context.Context, *UpdatePasswordReq) (*UpdatePasswordResp, error)
	// DeletePassword deletes the password.
	DeletePassword(context.Context, *DeletePasswordReq) (*DeletePasswordResp, error)
	// ListPassword lists all password entries.
	ListPasswords(context.Context, *ListPasswordReq) (*ListPasswordResp, error)
	// Refresh Token-centric RPCs
	// ListRefresh lists all the refresh token entries for a particular user.
	ListRefreshForUser(context.Context, *ListRefreshForUserReq) (*ListRefreshForUserResp, error)
	// RevokeRefresh revokes the refresh token for the provided user-client pair.
	RevokeRefresh(context.Context, *RevokeRefreshReq) (*RevokeRefreshResp, error)
	// VerifyPassword returns whether a password matches a hash for a specific email or not.
	VerifyPassword(context.Context, *VerifyPasswordReq) (*VerifyPasswordResp, error)
	// Misc RPCs
	// GetVersion returns version information of the server.
	GetVersion(context.Context, *VersionReq) (*VersionResp, error)
}

// UnimplementedDexServer can be embedded to have forward compatible implementations.
type UnimplementedDexServer struct {
}

func (*UnimplementedDexServer) CreateClient(ctx context.Context, req *CreateClientReq) (*CreateClientResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedDexServer) UpdateClient(ctx context.Context, req *UpdateClientReq) (*UpdateClientResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClient not implemented")
}
func (*UnimplementedDexServer) DeleteClient(ctx context.Context, req *DeleteClientReq) (*DeleteClientResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (*UnimplementedDexServer) CreatePassword(ctx context.Context, req *CreatePasswordReq) (*CreatePasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePassword not implemented")
}
func (*UnimplementedDexServer) UpdatePassword(ctx context.Context, req *UpdatePasswordReq) (*UpdatePasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (*UnimplementedDexServer) DeletePassword(ctx context.Context, req *DeletePasswordReq) (*DeletePasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassword not implemented")
}
func (*UnimplementedDexServer) ListPasswords(ctx context.Context, req *ListPasswordReq) (*ListPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPasswords not implemented")
}
func (*UnimplementedDexServer) ListRefreshForUser(ctx context.Context, req *ListRefreshForUserReq) (*ListRefreshForUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRefreshForUser not implemented")
}
func (*UnimplementedDexServer) RevokeRefresh(ctx context.Context, req *RevokeRefreshReq) (*RevokeRefreshResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeRefresh not implemented")
}
func (*UnimplementedDexServer) VerifyPassword(ctx context.Context, req *VerifyPasswordReq) (*VerifyPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (*UnimplementedDexServer) GetVersion(ctx context.Context, req *VersionReq) (*VersionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterDexServer(s *grpc.Server, srv DexServer) {
	s.RegisterService(&_Dex_serviceDesc, srv)
}

func _Dex_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).CreateClient(ctx, req.(*CreateClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/UpdateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).UpdateClient(ctx, req.(*UpdateClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).DeleteClient(ctx, req.(*DeleteClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_CreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).CreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/CreatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).CreatePassword(ctx, req.(*CreatePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).UpdatePassword(ctx, req.(*UpdatePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/DeletePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).DeletePassword(ctx, req.(*DeletePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_ListPasswords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).ListPasswords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/ListPasswords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).ListPasswords(ctx, req.(*ListPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_ListRefreshForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefreshForUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).ListRefreshForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/ListRefreshForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).ListRefreshForUser(ctx, req.(*ListRefreshForUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_RevokeRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRefreshReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).RevokeRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/RevokeRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).RevokeRefresh(ctx, req.(*RevokeRefreshReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/VerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).VerifyPassword(ctx, req.(*VerifyPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Dex/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).GetVersion(ctx, req.(*VersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha1.Dex",
	HandlerType: (*DexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _Dex_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _Dex_UpdateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _Dex_DeleteClient_Handler,
		},
		{
			MethodName: "CreatePassword",
			Handler:    _Dex_CreatePassword_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Dex_UpdatePassword_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _Dex_DeletePassword_Handler,
		},
		{
			MethodName: "ListPasswords",
			Handler:    _Dex_ListPasswords_Handler,
		},
		{
			MethodName: "ListRefreshForUser",
			Handler:    _Dex_ListRefreshForUser_Handler,
		},
		{
			MethodName: "RevokeRefresh",
			Handler:    _Dex_RevokeRefresh_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _Dex_VerifyPassword_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Dex_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1alpha1/api.proto",
}
